config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :signs
  resources :steps
  resources :information_signs
  post 'detects', to: 'detects#show'
  get 'detects', to: 'detects#new'
  get 'main', to: 'main#show'
  root 'main#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount API::Base => '/api'
  mount GrapeSwaggerRails::Engine => '/swagger'
end

app/controllers/main_controller.rb
# frozen_string_literal: true

class MainController < ApplicationController
  layout 'main/main_main'
  def show; end
end

app/views/main/show.html.erb
<div style="margin-left: 52em">
  <%= image_tag('redis_rails.png', :size => "200x100", :crop => :fill) %>
</div>

<style>
    .custom-menu {
        display: inline-block;
        width: 17em; 
        border: 2px solid gray;
        border-radius: 1em;
        color: #333;
        font-size: 1.5em;
        margin-left: 6em;
        text-align: center;
    }
    .pure-menu-link:hover {
    background-color: #eee;
    border-radius: 1em;
}

</style>

<div class="pure-menu custom-menu" >
    <span class="pure-menu-heading">Панель навигации</span>
    <ul class="pure-menu-list">
        <li class="pure-menu-item">
            <a href=<%= steps_path %> class="pure-menu-link">Движущихся объекты</a>
        </li>
        <li class="pure-menu-item">
            <a href=<%= signs_path %> class="pure-menu-link">Статические объекты</a>
        </li>
        <li class="pure-menu-item">
            <a href='/information_signs' class="pure-menu-link">Информация об объектах</a>
        </li>
        <li class="pure-menu-item">
            <a href='/detects' class="pure-menu-link">Детектировать объект</a>
        </li>
    </ul>
</div>

<div class="pure-g">
    <div class="pure-u-1-2" style="margin-top: 4em">
      <p>
        <%= image_tag('yolo.png', :size => "140x70", :crop => :fill) %>
      </p>
    </div>
    <div class="pure-u-1-2">
      <p>
        <%= image_tag('drulev.png', :size => "600x165", :crop => :fill) %>
      </p>
    </div>
</div>