config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :signs
  resources :steps
  resources :information_signs
  post 'detects', to: 'detects#show'
  get 'detects', to: 'detects#new'
  get 'main', to: 'main#show'
  root 'main#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount API::Base => '/api'
  mount GrapeSwaggerRails::Engine => '/swagger'
end

app/models/sign.rb
# frozen_string_literal: true

class Sign < ApplicationRecord
  belongs_to :document
  validates :document, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true

  validate :uniq_coordinates

  private

  def uniq_coordinates
    errors.add('Объект', 'присутствует по данным координатам') if Sign.exists?(latitude: latitude, longitude: longitude) && Sign.find_by(latitude: latitude, longitude: longitude) != self
  end
end

app/controllers/signs_controller.rb
# frozen_string_literal: true

class SignsController < ApplicationController
  layout 'signs/main_signs'
  before_action :set_sign, only: %i[show edit update destroy]

  # GET /signs or /signs.json
  def index
    @signs = Sign.all.order(:id).reverse
  end

  # GET /signs/1 or /signs/1.json
  def show; end

  # GET /signs/new
  def new
    @sign = Sign.new
  end

  # GET /signs/1/edit
  def edit; end

  # POST /signs or /signs.json
  def create
    document = Document.create!(filename: sign_image.original_filename,
                                content_type: sign_image.content_type,
                                head: sign_image.headers,
                                tempfile: sign_image.tempfile.read)
    @sign = Sign.new(sign_params.as_json.merge(document_id: document.id))

    respond_to do |format|
      if @sign.save
        format.html { redirect_to @sign, notice: 'Статический объект успешно создан.' }
        format.json { render :show, status: :created, location: @sign }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signs/1 or /signs/1.json
  def update
    if params[:image].present?
      @sign.document.update!(filename: sign_image.original_filename,
                             content_type: sign_image.content_type,
                             head: sign_image.headers,
                             tempfile: sign_image.tempfile.read)
    end

    respond_to do |format|
      if @sign.update(sign_params.as_json)
        format.html { redirect_to @sign, notice: 'Статический объект успешно обновлен.' }
        format.json { render :show, status: :ok, location: @sign }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signs/1 or /signs/1.json
  def destroy
    @sign.destroy
    respond_to do |format|
      format.html { redirect_to signs_url, notice: 'Статический объект успешно удален.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_sign
    @sign = Sign.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def sign_params
    params.require(:sign).permit(:longitude, :latitude, :name, :desc)
  end

  def sign_image
    params.require(:sign).fetch(:image)
  end
end

app/helpers/signs_helper.rb
# frozen_string_literal: true

module SignsHelper
end

app/views/signs/_form.html.erb
<%= form_with(model: sign, local: true) do |form| %>
  <% if sign.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sign.errors.count, "error") %> prohibited this sign from being saved:</h2>

      <ul>
      <% sign.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/signs/edit.html.erb
<h1>Редактирование статического объекта</h1>

<%= form_for(@sign, html: {class: 'pure-form pure-form-stacked', multipart: true }) do |form| %>
  <p><label for = "sign_id"><%= "Идентификатор: #{@sign.id}"%></label>
  <div>
    <p><label for = "sign_longitude">Долгота</label>
    <%= number_field 'sign', 'longitude', step: :any %></p>
  </div>

  <div>
    <p><label for = "sign_latitude">Широта</label>
    <%= number_field 'sign', 'latitude', step: :any %></p>
  </div>

  <div>
    <p><label for = "sign_name">Имя объекта</label>
    <%= text_field 'sign', 'name' %></p>
  </div>

  <div>
    <p><label for = "sign_desc">Описание</label>
    <%= text_field 'sign', 'desc' %></p>
  </div>

  <div class="pure-input-rounded">
    <p><label for = "sign_image">Изображение</label>
     <%= file_field 'sign', 'image' %>
    </p>
  </div>

  <button type="submit" class="pure-button pure-button-primary">Сохранить</button>
<% end %>
<style>
    .custom-restricted-width {
        display: inline-block;
        width: 17em; 
        border: 1px solid gray;
        border-radius: 4px;
    }
</style>
<div class="pure-menu custom-restricted-width">
  <ul class="pure-menu-list">
    <li class="pure-menu-item">
        <a href=<%="/signs/#{@sign.id}" %> class="pure-menu-link">Показать</a>
        <a href=<%=signs_path %> class="pure-menu-link">Назад</a>
    </li>
  </ul>
</div>

app/views/signs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Статические объекты</h1>

  <table class="pure-table pure-table-horizontal">
    <thead>
      <th>Идентификатор</th>
      <th>Имя</th>
      <th>Долгота</th>
      <th>Широта</th>
    </thead>
    <tbody>
      <% @signs.each do |sign| %>
        <tr>
        <td><%= sign.id %></td>
        <td><%= sign.name.present? ? sign.name : 'Имя не указано' %></td>
        <td><%= sign.longitude %></td>
        <td><%= sign.latitude %></td>
        <td><a href=<%= "/signs/#{sign.id}" %> class="pure-menu-link">Показать</a></td>
        <td><a href=<%= edit_sign_path(sign) %> class="pure-menu-link">Редактировать</a></td>
        <td><%= link_to 'Удалить', sign, class: "pure-menu-link" ,method: :delete, data: { confirm: 'Вы уверены?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<p>

<style>
    .custom-restricted-width {
        display: inline-block;
        width: 17em; 
        border: 1px solid gray;
        border-radius: 4px;
    }
</style>
<div class="pure-menu custom-restricted-width">
  <ul class="pure-menu-list">
    <li class="pure-menu-item">
        <a href=<%=new_sign_path%> class="pure-menu-link">Создать статический объект</a>
        <a href='/main' class="pure-menu-link">Главное меню</a>
    </li>
  </ul>
</div>

app/views/signs/new.html.erb
<h1>Новый статический объект</h1>


<%= form_for(@sign, html: { class: 'pure-form pure-form-stacked', multipart: true }) do |form| %>
  <div>
    <p><label for = "sign_longitude">Долгота</label>
    <%= number_field 'sign', 'longitude', step: :any, required: true %></p>
  </div>

  <div>
    <p><label for = "sign_latitude">Широта</label>
    <%= number_field 'sign', 'latitude', step: :any, required: true %></p>
  </div>

  <div>
    <p><label for = "sign_name">Имя объекта</label>
    <%= text_field 'sign', 'name' %></p>
  </div>

  <div>
    <p><label for = "sign_desc">Описание</label>
    <%= text_field 'sign', 'desc' %></p>
  </div>

  <div>
    <p><label for = "sign_image">Изображение</label>
     <%= file_field 'sign', 'image', required: true %>
    </p>
  </div>
  <button type="submit" class="pure-button pure-button-primary">Сохранить</button>
<% end %>
<br>
<style>
    .custom-restricted-width {
        display: inline-block;
        width: 15em; 
        border: 1px solid gray;
        border-radius: 4px;
    }
</style>
<div class="pure-menu custom-restricted-width">
  <ul class="pure-menu-list">
    <li class="pure-menu-item">
        <a href=<%=signs_path %> class="pure-menu-link">Назад</a>
    </li>
  </ul>
</div>

app/views/signs/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Данные статического объекта</h1>
<style>
    .custom-restricted-width {
        display: inline-block;
        width: 26em; 
        border: 1px solid gray;
        border-radius: 4px;
    }
</style>
<p>
  <div class="pure-menu custom-restricted-width">
    <ul class="pure-menu-list">
      <li class="pure-menu-item">
          <a href=<%= edit_sign_path(@sign) %> class="pure-menu-link">Редактировать</a>
          <a href=<%= url_for(:back) %> class="pure-menu-link">Назад</a>
      </li>
    </ul>
  </div>
</p>
<p>
  <b>Идентификатор:</b>
  <%= @sign.id %>
</p>

<p>
  <b>Имя:</b>
  <%= @sign.name.present? ? @sign.name : 'Имя не указано' %>
</p>

<p>
  <b>Долгота:</b>
  <%= @sign.longitude %>
</p>

<p>
  <b>Широта:</b>
  <%= @sign.latitude %>
</p>

<p>
  <b>Описание:</b>
  <%= @sign.desc.present? ? @sign.desc : 'Описания нет'%>
</p>

<p>
  <b> Изображение статического объекта</b>
  <p> 
    <img class="pure-img" src=<%= "data:image/jpeg;base64,#{Base64.encode64(@sign.document.tempfile).gsub("\n",'')}"%> alt="Избражение статического объекта" />
  </p>
</p>

<p>
  <b>Местонахождение:</b>
  <p>
    <!-- размеры вывода квадрата - 0.0004 --> 
    <iframe width="600" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" 
            src=<%="https://www.openstreetmap.org/export/embed.html?bbox=#{@sign.longitude - 0.0004}%2C#{@sign.latitude - 0.0004}%2C#{@sign.longitude + 0.0004}%2C#{@sign.latitude + 0.0004}&layer=mapnik&marker=#{@sign.latitude}%2C#{@sign.longitude}" %> 
            style="border: 1px solid black">
  </p>
</p>