config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :signs
  resources :steps
  resources :information_signs
  post 'detects', to: 'detects#show'
  get 'detects', to: 'detects#new'
  get 'main', to: 'main#show'
  root 'main#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount API::Base => '/api'
  mount GrapeSwaggerRails::Engine => '/swagger'
end

app/models/information_sign.rb
# frozen_string_literal: true

class InformationSign < ApplicationRecord
  before_create :default_height

  private

  def default_height
    self.height ||= 180
  end
end

app/controllers/information_signs_controller.rb
# frozen_string_literal: true

class InformationSignsController < ApplicationController
  layout 'information_signs/main_information_signs'
  before_action :set_information_sign, only: %i[show edit update destroy]

  # GET /information_signs or /information_signs.json
  def index
    @information_signs = InformationSign.all.order(:id).reverse
  end

  # GET /signs/1 or /signs/1.json
  def show; end

  # GET /signs/new
  def new
    @information_sign = InformationSign.new
  end

  # GET /signs/1/edit
  def edit; end

  # POST /signs or /signs.json
  def create
    @information_sign = InformationSign.new(information_sign_params.as_json)

    respond_to do |format|
      if @information_sign.save
        format.html { redirect_to @information_sign, notice: 'Информация о статическом объекте успешно созданa.' }
        format.json { render :show, status: :created, location: @information_sign }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @information_sign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signs/1 or /signs/1.json
  def update
    respond_to do |format|
      if @information_sign.update(information_sign_params.as_json)
        format.html { redirect_to @information_sign, notice: 'Информация о статическом объекте успешно обновлена.' }
        format.json { render :show, status: :ok, location: @information_sign }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @information_sign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signs/1 or /signs/1.json
  def destroy
    @information_sign.destroy
    respond_to do |format|
      format.html { redirect_to information_signs_url, notice: 'Информация о статическом объекте успешно удалена.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_information_sign
    @information_sign = InformationSign.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def information_sign_params
    params.require(:information_sign).permit(:name, :height)
  end
end

app/views/information_signs/edit.html.erb
<h1>Редактирование информации статического объекта</h1>

<%= form_for(@information_sign, html: {class: 'pure-form pure-form-stacked', multipart: true }) do |form| %>
  <p><label for = "information_sign_id"><%= "Идентификатор: #{@information_sign.id}"%></label>
  <div>
    <p><label for = "information_sign_name">Имя объекта</label>
    <%= text_field 'information_sign', 'name' %></p>
  </div>

  <div>
    <p><label for = "information_sign_name">Высота</label>
    <%= text_field 'information_sign', 'height' %></p>
  </div>

  <button type="submit" class="pure-button pure-button-primary">Сохранить</button>
<% end %>
<style>
    .custom-restricted-width {
        display: inline-block;
        width: 17em; 
        border: 1px solid gray;
        border-radius: 4px;
    }
</style>
<div class="pure-menu custom-restricted-width">
  <ul class="pure-menu-list">
    <li class="pure-menu-item">
        <a href=<%="/information_signs/#{@information_sign.id}" %> class="pure-menu-link">Показать</a>
        <a href=<%=information_signs_path %> class="pure-menu-link">Назад</a>
    </li>
  </ul>
</div>

app/views/information_signs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Информация о объектах</h1>

  <table class="pure-table pure-table-horizontal">
    <thead>
      <th>Идентификатор</th>
      <th>Имя</th>
      <th>Высота</th>
    </thead>
    <tbody>
      <% @information_signs.each do |sign| %>
        <tr>
        <td><%= sign.id %></td>
        <td><%= sign.name.present? ? sign.name : 'Имя не указано' %></td>
        <td><%= sign.height %></td>
        <td><a href=<%= "/information_signs/#{sign.id}" %> class="pure-menu-link">Показать</a></td>
        <td><a href=<%= edit_information_sign_path(sign) %> class="pure-menu-link">Редактировать</a></td>
        <td><%= link_to 'Удалить', sign, class: "pure-menu-link" ,method: :delete, data: { confirm: 'Вы уверены?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<p>

<style>
    .custom-restricted-width {
        display: inline-block;
        width: 17em; 
        border: 1px solid gray;
        border-radius: 4px;
    }
</style>
<div class="pure-menu custom-restricted-width">
  <ul class="pure-menu-list">
    <li class="pure-menu-item">
        <a href=<%=new_information_sign_path%> class="pure-menu-link">Создать инфомацию</a>
        <a href='/main' class="pure-menu-link">Главное меню</a>
    </li>
  </ul>
</div>

app/views/information_signs/new.html.erb
<h1>Новая информация статического объекта</h1>


<%= form_for(@information_sign, html: { class: 'pure-form pure-form-stacked', multipart: true }) do |form| %>
  <div>
    <p><label for = "information_sign_height">Высота</label>
    <%= number_field 'information_sign', 'height', step: :any, required: true %></p>
  </div>

  <div>
    <p><label for = "information_sign_name">Имя объекта</label>
    <%= text_field 'information_sign', 'name' %></p>
  </div>

  <button type="submit" class="pure-button pure-button-primary">Сохранить</button>
<% end %>
<br>
<style>
    .custom-restricted-width {
        display: inline-block;
        width: 15em; 
        border: 1px solid gray;
        border-radius: 4px;
    }
</style>
<div class="pure-menu custom-restricted-width">
  <ul class="pure-menu-list">
    <li class="pure-menu-item">
        <a href=<%=signs_path %> class="pure-menu-link">Назад</a>
    </li>
  </ul>
</div>

app/views/information_signs/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Информация статического объекта</h1>
<style>
    .custom-restricted-width {
        display: inline-block;
        width: 26em; 
        border: 1px solid gray;
        border-radius: 4px;
    }
</style>
<p>
  <div class="pure-menu custom-restricted-width">
    <ul class="pure-menu-list">
      <li class="pure-menu-item">
          <a href=<%= edit_information_sign_path(@information_sign) %> class="pure-menu-link">Редактировать</a>
          <a href=<%= url_for(:back) %> class="pure-menu-link">Назад</a>
      </li>
    </ul>
  </div>
</p>
<p>
  <b>Идентификатор:</b>
  <%= @information_sign.id %>
</p>

<p>
  <b>Имя:</b>
  <%= @information_sign.name.present? ? @information_sign.name : 'Имя не указано' %>
</p>
<p>
  <b>Высота:</b>
  <%= @information_sign.height %>
</p>